# Generated by Django 4.2.5 on 2023-09-28 02:26

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "to do": "An issue for which work has not yet been started",
        "in progress" : "An issue that is actively beign worked on",
        "done" : "An issie for which work has been completed"
    }

    Status = apps.get_model("issues", "Status")

    for key, value in entries.items():
        role_obj = Status(name = key, description = value)
        role_obj.save()



class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]